version: "2.1"

services:
  sonarqube:
    build: sonarqube
    #command: "tail -f /dev/null"
    #env_file: configuration.env
    ports:
      - '9000:9000'
    healthcheck:
      test: ["CMD-SHELL", "if [ \"`curl -s -f -u admin:admin http://localhost:9000/api/system/status | cut -f4 -d':' | tr -d '\",}'`\" = 'UP' ];then true;else false;fi"]
      interval: 10s
      timeout: 5s
      retries: 10
  scanner:
    build: scanner
    depends_on:
      sonarqube:
        condition: service_healthy
    #env_file: configuration.env
    links:
      - sonarqube
    command: >
      sh -c "sonar-scanner \
                     -Dsonar.host.url=http://sonarqube:9000 \
                     -Dsonar.projectBaseDir=/project \
                     -Dsonar.login=admin \
                     -Dsonar.password=admin"
